POST http://localhost:3000/login/ 
Content-Type: application/json 

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###

GET http://localhost:3000/states/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk1NjY0NDE5fQ.LcQO-yFNYQCgES4MoQgAXDYC8KoIbNOVe25udf5nurs 

### 

GET http://localhost:3000/states/8/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk1NjY0NDE5fQ.LcQO-yFNYQCgES4MoQgAXDYC8KoIbNOVe25udf5nurs 

### 

GET http://localhost:3000/states/8/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk1NjY0NDE5fQ.LcQO-yFNYQCgES4MoQgAXDYC8KoIbNOVe25udf5nurs

